// Build labs.html: every experiment in the leaf editor's lab drawer, with a link that runs it.
//
//   npm run labs          rewrites labs.html from draw.html
//
// THE LIST IS READ OFF THE EDITOR, NOT WRITTEN BY HAND. The drawer is the source: every lab
// is a `.res-btn` with an id, a three-letter data-code and a title, sitting under a heading
// whose note explains the group. This loads draw.html in headless Chromium and reads those
// the way the editor's own ?lab= catalogue does (the heading found by walking up from the
// button, the injected code chips stripped), so the page says what the drawer says. The
// smoke test fails when the two drift apart, and running this again is the fix.

import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

export async function readLabs(base) {
  const launch = { args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] };
  if (process.env.CHROMIUM_PATH) launch.executablePath = process.env.CHROMIUM_PATH;
  const browser = await chromium.launch(launch);
  const page = await browser.newPage();
  await page.goto(new URL('draw.html', base).href, { waitUntil: 'load' });
  await page.waitForTimeout(800);
  const labs = await page.evaluate(() => {
    const text = el => { const c = el.cloneNode(true); for (const s of c.querySelectorAll('.lab-code')) s.remove();
                         return (c.textContent || '').replace(/\s+/g, ' ').trim(); };
    const headingOf = btn => { const g = btn.closest('.group'); let t = g && g.querySelector('.menu-title'), p = g && g.parentElement;
                               while (!t && p) { t = p.querySelector && p.querySelector('.menu-title'); p = p.parentElement; } return t; };
    return [...document.querySelectorAll('.res-btn[id]')].map(btn => {
      const h = headingOf(btn), grp = h && h.closest('.group');
      return {
        id: btn.id, code: (btn.dataset.code || '').toLowerCase(), label: text(btn),
        about: (btn.getAttribute('title') || '').split('\n\n?lab=')[0].replace(/\s+/g, ' ').trim(),
        group: h ? text(h) : '', note: grp ? [...grp.querySelectorAll(':scope > .menu-note')].map(text).join(' ') : '',
        drawer: !!btn.closest('#paneLab'),
      };
    });
  });
  await browser.close();
  return labs;
}

const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
// The first sentence stands as the summary; the rest waits behind "more". A div, not a p: a p
// cannot hold <details>, and the parser closes it early and strands the toggle on a line of its own.
function splitNote(note) {
  const m = note.match(/^(.{40,}?[.!?])\s+(?=[A-Z(“"'])/);
  return m ? [m[1], note.slice(m[0].length)] : [note, ''];
}

export function render(labs) {
  const groups = [];
  for (const l of labs) {
    // The live morph's controls are addressable labs too, but they sit in the morph bar rather
    // than the drawer and have no heading of their own.
    const name = l.group || (l.drawer ? 'other' : 'the live morph');
    let g = groups.find(x => x.name === name);
    if (!g) groups.push(g = { name, note: l.group ? l.note : 'The controls of a running morph, which sit in the bar under the canvas rather than in the drawer. They act on the morph that is live, so they do nothing until one is: select two or more shapes, press morph in the toolbar, then live.', labs: [] });
    g.labs.push(l);
  }
  const sections = groups.map((g, i) => {
    const [first, rest] = splitNote(g.note || '');
    const rows = g.labs.map(l => `
      <li class="lab" data-q="${esc((l.code + ' ' + l.label + ' ' + l.about + ' ' + g.name).toLowerCase())}">
        <a class="run" href="draw.html?lab=${esc(l.code)}" title="open the editor and run ${esc(l.label)}"><span class="code">${esc(l.code)}</span>${esc(l.label)}</a>
        <p>${esc(l.about)}</p>
      </li>`).join('');
    return `
  <section class="group" id="g${i + 1}">
    <div class="sec-head"><h2>${esc(g.name)}</h2><div class="rule"></div><span class="n">${g.labs.length} lab${g.labs.length > 1 ? 's' : ''}</span></div>
    ${first ? `<div class="sec-note">${esc(first)}${rest ? ` <details><summary>more</summary>${esc(rest)}</details>` : ''}</div>` : ''}
    <ul class="labs">${rows}
    </ul>
  </section>`;
  }).join('');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>tvf labs</title>
<meta name="description" content="Every experiment in the leaf editor's lab drawer, with a link that opens the editor and runs it.">
<!-- GENERATED by tools/build-labs.mjs from draw.html: do not edit here. Run \`npm run labs\`. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="gallery/style.css">
</head>
<body class="page-labs">
<header>
  <nav class="crumbs"><a href="draw.html">← the editor</a> · <a href="gallery/index.html">the galleries</a></nav>
  <h1>tvf <em>labs</em> <span class="pill">${labs.length} labs</span></h1>
  <p class="lede">
    The leaf editor's lab drawer holds the <b>experiments</b>: instruments that measure the format rather than
    make shapes with it, test suites that print their own numbers, and figures laid out for a paper. Each
    one has a three-letter code, and <code>draw.html?lab=<i>code</i></code> opens the editor and runs it.
    Every lab is listed below under its drawer heading, with what it does and a link that runs it.
  </p>
  <p class="sub">
    Some labs act on what is already on the canvas (the repair tools work on the selected shape, the
    walker walks the current scene), so open those with something drawn. The descriptions are the
    buttons' own tooltips and the group notes are the drawer's, so this page says what the drawer says.
  </p>
</header>
<div class="bar"><div class="bar-in">
  <input id="q" type="search" placeholder="filter: a code, a word, a heading" aria-label="filter the labs" autocomplete="off">
  <span class="count" id="count">${labs.length} labs</span>
  <div class="spacer"></div>
  <a class="jump" href="draw.html?lab=list" title="open the editor with the lab drawer listed">open the drawer</a>
</div></div>
<main>${sections}
  <p class="none" id="none" hidden>No lab matches that.</p>
</main>
<footer>
  Generated from <b>draw.html</b> by <code>tools/build-labs.mjs</code>. A lab's code is its button's
  <code>data-code</code>; the longer code derived from its id (<code>bStreamBank</code> → <code>stream-bank</code>)
  works in <code>?lab=</code> too.
</footer>
<script>
// Filter as you type: a lab shows when every word you typed is somewhere in its code, label,
// description or heading; a heading shows while any of its labs do.
const q = document.getElementById('q'), count = document.getElementById('count'), none = document.getElementById('none');
q.addEventListener('input', () => {
  const words = q.value.toLowerCase().split(/\\s+/).filter(Boolean);
  let shown = 0;
  for (const sec of document.querySelectorAll('section.group')) {
    let any = false;
    for (const li of sec.querySelectorAll('li.lab')) {
      const ok = words.every(w => li.dataset.q.includes(w));
      li.hidden = !ok; if (ok) { any = true; shown++; }
    }
    sec.hidden = !any;
  }
  count.textContent = words.length ? shown + ' of ${labs.length}' : '${labs.length} labs';
  none.hidden = shown > 0;
});
</script>
</body>
</html>
`;
}

// Run as a script: serve the repo, read the labs, write labs.html.
if (import.meta.url === `file://${process.argv[1]}`) {
  const server = createServer(async (req, res) => {
    const p = normalize(decodeURIComponent(new URL(req.url, 'http://x').pathname)).replace(/^([/\\])+/, '');
    try { res.writeHead(200, { 'Content-Type': p.endsWith('.css') ? 'text/css' : 'text/html' }); res.end(await readFile(join(ROOT, p))); }
    catch { res.writeHead(404); res.end(); }
  });
  await new Promise(ok => server.listen(0, '127.0.0.1', ok));
  const labs = await readLabs(`http://127.0.0.1:${server.address().port}/`);
  server.close();
  await writeFile(join(ROOT, 'labs.html'), render(labs));
  console.log(`labs.html: ${labs.length} labs`);
}
